<a href="https://colab.research.google.com/github/Denis04-M/phishing-lab/blob/main/phishing_lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from warnings import simplefilter

import numpy as np
import pandas as pd
import sklearn
from numpy import genfromtxt
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeRegressor
#from sklearn.datasets import fetch_mldata
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (accuracy_score, confusion_matrix, f1_score,
                             precision_score, recall_score)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

simplefilter(action='ignore', category=FutureWarning)

###############################################################


feature=genfromtxt('phishing.csv',delimiter=',',usecols=(i for i in range(0,31)),skip_header=1)
target=genfromtxt('phishing.csv',delimiter=',',usecols=(-1),skip_header=1)
sc = StandardScaler()
sc.fit(feature)
target_label = LabelEncoder().fit_transform(target)
feature_std = sc.transform(feature)
x_train, x_test, y_train, y_test = train_test_split(feature_std, target_label, test_size=0.5, random_state=1)

print("Begin:__________________________________")
###################################################
## print stats 
precision_scores_list = []
accuracy_scores_list = []

def print_stats_metrics(y_test, y_pred):    
    print('Accuracy: %.2f' % accuracy_score(y_test,   y_pred) )
    #Accuracy: 0.84
    accuracy_scores_list.append(accuracy_score(y_test,   y_pred) )
    confmat = confusion_matrix(y_true=y_test, y_pred=y_pred)
    print ("confusion matrix")
    print(confmat)
    print (pd.crosstab(y_test, y_pred, rownames=['True'], colnames=['Predicted'], margins=True))
    precision_scores_list.append(precision_score(y_true=y_test, y_pred=y_pred))
    print('Precision: %.3f' % precision_score(y_true=y_test, y_pred=y_pred))
    print('Recall: %.3f' % recall_score(y_true=y_test, y_pred=y_pred))
    print('F1-measure: %.3f' % f1_score(y_true=y_test, y_pred=y_pred))


########################Logistic Regression##############################
print("########################Logistic Regression##############################")
clfLog = LogisticRegression()
clfLog.fit(x_train,y_train)
predictions = clfLog.predict(x_test)
print_stats_metrics(y_test, predictions)

########################Random Forest##############################
print("########################Random Forest##############################")
clfRandForest = RandomForestClassifier()
clfRandForest.fit(x_train,y_train)
predictions = clfRandForest.predict(x_test)
print_stats_metrics(y_test, predictions)
#######################Decision Tree#######################
print("#######################Decision Tree#######################")
clfDT = DecisionTreeRegressor()
clfDT.fit(x_train,y_train)
predictions = clfDT.predict(x_test)
print_stats_metrics(y_test, predictions)
#######################Naive Bayes#######################
print("#######################Naive Bayes#######################")
clfNB = GaussianNB()
clfNB.fit(x_train,y_train)
predictions = clfNB.predict(x_test)
print_stats_metrics(y_test, predictions)




Begin:__________________________________
########################Logistic Regression##############################
Accuracy: 1.00
confusion matrix
[[2464    0]
 [   0 3064]]
Predicted     0     1   All
True                       
0          2464     0  2464
1             0  3064  3064
All        2464  3064  5528
Precision: 1.000
Recall: 1.000
F1-measure: 1.000
########################Random Forest##############################
Accuracy: 1.00
confusion matrix
[[2464    0]
 [   0 3064]]
Predicted     0     1   All
True                       
0          2464     0  2464
1             0  3064  3064
All        2464  3064  5528
Precision: 1.000
Recall: 1.000
F1-measure: 1.000
#######################Decision Tree#######################
Accuracy: 1.00
confusion matrix
[[2464    0]
 [   0 3064]]
Predicted   0.0   1.0   All
True                       
0          2464     0  2464
1             0  3064  3064
All        2464  3064  5528
Precision: 1.000
Recall: 1.000
F1-measure: 1.000
#############

In [ ]:
print('Recall_score: %.2f' % recall_score(y_test, predictions) )
print('Precision_score: %.2f' % precision_score(y_test, predictions) )
print('F1_score: %.2f' % f1_score(y_test, predictions) )

Recall_score: 1.00
Precision_score: 0.56
F1_score: 0.72


In [ ]:
#import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
import pandas as pd
from numpy import genfromtxt
from sklearn import datasets
#from sklearn.datasets import fetch_mldata
from sklearn.model_selection import train_test_split
import sklearn
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score, f1_score
import pandas as pd
import matplotlib.pyplot as plt

###############################################################

learning_rate = 0.001
n_epochs = 200
batch_size = 100

def convertOneHot(data):
    y_onehot=[0]*len(data)
    for i,j in enumerate(data):
        y_onehot[i]=[0]*(data.max()+1)
        y_onehot[i][j]=1
    return y_onehot

###############################################################
feature=genfromtxt('phishing.csv',delimiter=',',usecols=(i for i in range(0,31)),skip_header=1)
target=genfromtxt('phishing.csv',delimiter=',',usecols=(-1),skip_header=1)
sc = StandardScaler()
sc.fit(feature)
target_label = LabelEncoder().fit_transform(target)
target_onehot = convertOneHot(target_label)
feature_std = sc.transform(feature)
x_train, x_test, y_train_onehot, y_test_onehot = train_test_split(feature_std, target_onehot, test_size=0.20, random_state=0)
A=x_train.shape[1]
B=len(y_train_onehot[0])
print(len(y_test_onehot[0]))
print(B)
print("Begin:__________________________________")
#####################################################################

def plot_metric_per_epoch():
    x_epochs = []
    y_epochs = [] 
    for i, val in enumerate(accuracy_scores_list):
        x_epochs.append(i)
        y_epochs.append(val)
    
    plt.scatter(x_epochs, y_epochs,s=50,c='lightgreen', marker='s', label='score')
    plt.xlabel('epoch')
    plt.ylabel('score')
    plt.title('Score per epoch')
    plt.legend()
    plt.grid()
    plt.show()

###################################################
## print stats 
precision_scores_list = []
accuracy_scores_list = []

def print_stats_metrics(y_test, y_pred):    
    print('Accuracy: %.2f' % accuracy_score(y_test,   y_pred) )
    #Accuracy: 0.84
    accuracy_scores_list.append(accuracy_score(y_test,   y_pred) )
    confmat = confusion_matrix(y_true=y_test, y_pred=y_pred)
    print ("confusion matrix")
    print(confmat)
    print (pd.crosstab(y_test, y_pred, rownames=['True'], colnames=['Predicted'], margins=True))
    precision_scores_list.append(precision_score(y_true=y_test, y_pred=y_pred))
    print('Precision: %.3f' % precision_score(y_true=y_test, y_pred=y_pred))
    print('Recall: %.3f' % recall_score(y_true=y_test, y_pred=y_pred))
    print('F1-measure: %.3f' % f1_score(y_true=y_test, y_pred=y_pred))


###############################################################
def layer(input, weight_shape, bias_shape):
    weight_stddev = (2.0/weight_shape[0])**0.5
    w_init = tf.random_normal_initializer(stddev=weight_stddev)
    bias_init = tf.constant_initializer(value=0)
    W = tf.get_variable("W", weight_shape, initializer=w_init)
    b = tf.get_variable("b", bias_shape, initializer=bias_init)
    return tf.nn.relu(tf.matmul(input, W) + b)
###############################################################
def inference_deep_layers(x_tf, A, B):
    with tf.variable_scope("hidden_1"):
        hidden_1 = layer(x_tf, [A, 15],[15])
    with tf.variable_scope("hidden_2"):
        hidden_2 = layer(hidden_1, [15, 5],[5])
    with tf.variable_scope("output"):
        output = layer(hidden_2, [5, B], [B])
    return output
###############################################################
def loss_deep(output, y_tf):
    xentropy = tf.nn.softmax_cross_entropy_with_logits(logits=output, labels=y_tf)
    loss = tf.reduce_mean(xentropy) 
    return loss
###########################################################

def training(cost):
    optimizer = tf.train.GradientDescentOptimizer(learning_rate)
    train_op = optimizer.minimize(cost)
    return train_op

###########################################################
def evaluate(output, y_tf):
    correct_prediction = tf.equal(tf.argmax(output,1), tf.argmax(y_tf,1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, "float"))
    return accuracy
###############################################################

x_tf = tf.placeholder("float",[None,A])
y_tf = tf.placeholder("float",[None,B])
###############################################################
output = inference_deep_layers(x_tf,A,B)
cost = loss_deep(output,y_tf)
train_op=training(cost)
eval_op=evaluate(output,y_tf)
###############################################################
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
###############################################################
y_p_metrics = tf.argmax(output,1)
###############################################################
num_samples_train_set=x_train.shape[0]
num_batches = int(num_samples_train_set/batch_size)

###############################################################

for i in range(n_epochs):
    print("epoch %s out of %s"%(i,n_epochs))
    for batch_n in range(num_batches):
        sta = batch_n*batch_size
        end = sta+batch_size
        sess.run(train_op,feed_dict={x_tf:x_train[sta:end],y_tf:y_train_onehot[sta:end]})
    print ("-------------------------------------------------------------------------------")    
    print ("Accuracy score")
    #result = sess.run(eval_op,feed_dict={x_tf:x_test,y_tf:y_test_onehot})
    result, y_result_metrics = sess.run([eval_op, y_p_metrics], feed_dict={x_tf: x_test, y_tf: y_test_onehot})
    print("Run {},{}".format(i,result))
    y_true = np.argmax(y_test_onehot,1)
    print_stats_metrics(y_true, y_result_metrics)
    if i==n_epochs-1:
        plot_metric_per_epoch()


In [ ]:

      neighbors.append(node)


In [ ]:
import string
# 1
def perSentence():
  word_count = 0

  # open file
  with open('text.txt') as text_file:
    text = text_file.read()

  # spliting the text into sentences
  sentences = text.split('.\n')
  sentence_count = len(sentences)

  for sentence in sentences:

      # removing punctuations
      lines = sentence.translate(str.maketrans('', '', string.punctuation))

      # spliting sentences into words
      words = lines.split()

      word_count += len(words)

  print(f'Number of sentences = {sentence_count}')
  print(f'Number of words = {word_count}')
  print('Number of words per sentence = ', (word_count//sentence_count))

  return (word_count//sentence_count)


# 2
def uniqueWords():

  unique_words = set()

  # open file
  with open('unique.txt') as text_file:
    text = text_file.read()

  # removing punctuations
  words = lines = text.translate(str.maketrans('', '', string.punctuation)).split()

  for word in words:
    # add words to set
    unique_words.add(word)

  print(f'\n The unique words are:')
  for u_word in unique_words:
    print(' *', u_word)

  return unique_words



# 3

def wordFrequency():

  word_freq = {}
  unique_words = set()

  with open('unique.txt') as text_file:
    text = text_file.read()

  # removing punctuations
  words = lines = text.translate(str.maketrans('', '', string.punctuation)).split()

  # add words to set
  for word in words:
    unique_words.add(word)

  for u_word in unique_words:
    # count word frequency
    n = words.count(u_word)
    # add word and word frequency to dict.
    word_freq.update({u_word:n})

  print('\n', word_freq)

  return word_freq

if __name__ == "__main__":
  perSentence()
  uniqueWords()
  wordFrequency()


Number of sentences = 11
Number of words = 260
Number of words per sentence =  23

 The unique words are:
 * interpreted
 * language
 * unique
 * therefore
 * maybe
 * is
 * an
 * programming
 * stack
 * a
 * generalpurpose
 * Python
 * highlevel
 * overflow
 * Trial
 * Maybe
 * Triathlon
 * trial

 {'interpreted': 1, 'language': 2, 'unique': 1, 'therefore': 1, 'maybe': 2, 'is': 2, 'an': 1, 'programming': 1, 'stack': 1, 'a': 1, 'generalpurpose': 1, 'Python': 2, 'highlevel': 1, 'overflow': 1, 'Trial': 2, 'Maybe': 1, 'Triathlon': 1, 'trial': 2}


In [ ]:
def uniqueWords():

  unique_words = set()

  # open file
  with open('unique.txt') as text_file:
    text = text_file.read()

  # removing punctuations
  words = lines = text.translate(str.maketrans('', '', string.punctuation)).split()

  for word in words:
    # add words to set
    unique_words.add(word)

  print(f'The unique words are:')
  for u_word in unique_words:
    print(' *', u_word)

  return None

uniqueWords()

The unique words are:
 * trial
 * interpreted
 * maybe
 * Triathlon
 * an
 * programming
 * language
 * stack
 * Python
 * Maybe
 * highlevel
 * therefore
 * Trial
 * overflow
 * is
 * generalpurpose
 * unique
 * a


In [ ]:
def wordFrequency():

  word_freq = {}
  unique_words = set()

  with open('unique.txt') as text_file:
    text = text_file.read()

  # removing punctuations
  words = lines = text.translate(str.maketrans('', '', string.punctuation)).split()

  # add words to set
  for word in words:
    unique_words.add(word)

  for u_word in unique_words:
    # count word frequency
    n = words.count(u_word)
    # add word and word frequency to dict.
    word_freq.update({u_word:n})

  print(word_freq)

  return None

wordFrequency()

{'trial': 2, 'interpreted': 1, 'maybe': 2, 'Triathlon': 1, 'an': 1, 'programming': 1, 'language': 2, 'stack': 1, 'Python': 2, 'Maybe': 1, 'highlevel': 1, 'therefore': 1, 'Trial': 2, 'overflow': 1, 'is': 2, 'generalpurpose': 1, 'unique': 1, 'a': 1}


In [ ]:
words

['Python',
 'is',
 'an',
 'interpreted',
 'highlevel',
 'generalpurpose',
 'programming',
 'language',
 'Python',
 'is',
 'a',
 'language',
 'therefore',
 'Trial',
 'unique',
 'stack',
 'overflow',
 'Trial',
 'trial',
 'trial',
 'Triathlon',
 'Maybe',
 'maybe',
 'maybe']